### ISSUE TITLE
Declare module specific R libraries 

### ISSUE THREAD

**Issue by gaow** [stephenslab/dsc-log-fold-change#2]
@jhsiao999  I've got 2 comments for `DESeq2` module:

1. You might want to add a `@CONF: R_libs=DESeq2` or `@CONF: R_libs = DESeq2, voom, ...` if there are more libraries used. That way the library not only gets automatically installed when others run it, but also gets loaded. Otherwise even your code as is would not work due to missing load lib statements.

2. Maybe consider putting the code under `code` folder instead? See my `get_data.R` example

Now you can make the changes and add your module to `benchmark.dsc` and give it a go using `--target get_data * run_DESeq2` :)

**Comment by jhsiao999** [comment]
Great. Thanks. I've made changes accordingly. Will push the changes now.

**Comment by gaow** [comment]
Looking good! except  [here](https://github.com/stephenslab/dsc-log-fold-change/blob/master/code/run_DESeq2.R#L5) (and the line under it) will have to be conventional R variable, so remove `$()`. After that it should run?

**Comment by jhsiao999** [comment]
I got this error message:
```
ERROR: sequence item 0: expected str instance, NoneType found
```

**Comment by jhsiao999** [comment]
this the line I ran to test my code

```
dsc benchmark.dsc --target "get_data*DESeq2" --truncate -o testDESeq2
```

**Comment by gaow** [comment]
@jhsiao999 oops sorry, fixed in `master`. Please update. But there is still issue with your data column names ... you can run to find out.
